services: docker
language: python
jobs:
  include:
    - stage: build 
      script:
        - docker build  --tag c3genomics/ncov-tools .
    - stage: login
      script:
        - ./.docker_login
    
    - stage: deploy       
      - script:
         -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:alpha
         -  docker push c3genomics/ncov-tools:alpha
       on:
         condition: branch NOT IN (master)
      - script:
         -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:beta
         -  docker push c3genomics/ncov-tools:beta
       on:
         branch: master
      - script:
         -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:$TRAVIS_TAG
         -  docker push c3genomics/ncov-tools:$TRAVIS_TAG
       on:
         tags: true
