services: docker
language: python
script:
  -  docker pull c3genomics/ncov-tools:alpha || echo no alpha image in the repo
  -  docker build  --tag c3genomics/ncov-tools .
after_success:
  - ./.docker_login
  -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:alpha
  -  docker push c3genomics/ncov-tools:alpha 
deploy:
  - provider: script
    script:
        -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:$TRAVIS_TAG
        -  docker push c3genomics/ncov-tools:$TRAVIS_TAG 
        -  docker push c3genomics/ncov-tools:latest
    on:
      tags: true
  - provider: script
    script:
      -  docker tag c3genomics/ncov-tools c3genomics/ncov-tools:beta
      -  docker push c3genomics/ncov-tools:beta
    on:
        branch: master
