name: ncov-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - mafft
  - augur
  - pysam
  - r
  - bioconductor-ggtree
  - r-patchwork
  - r-ggforce
  - bedtools
  - samtools
  - newick_utils
